name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Скрипт сработает при пуше в ветку main

permissions:
  contents: write  # Нужно для записи в ветку gh-pages
  pages: write     # Нужно для управления настройками Pages
  id-token: write  # Нужно для подтверждения личности в GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        # Используем npm ci для стабильности, если есть lock-файл
        run: npm ci || npm install

      - name: Build project
        run: npm run build
        env:
          CI: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist 
          publish_branch: gh-pages
          force_orphan: true